name: 'reporting_project'
version: '1.0.0'
config-version: 2

profile: 'reporting_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  reporting_project:
    +materialized: table     # ❗ REMOVE schema override

seeds:
  reporting_project:
    +quote_columns: true     # ❗ REMOVE schema override
